version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "81:80"      # Exposing internal port 80 on host port 81 (optional if you only want tunnel access)
      - "8080:8080"
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      SKIP_DOMAIN_VALIDATION: true
      APACHE_ADDITIONAL_NETWORK: ""

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - nextcloud
    # The command below will run the tunnel named "nextcloud" (see steps below)
    command: tunnel run nextcloud
    volumes:
      - ./.cloudflared:/home/nonroot/.cloudflared

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer