version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"      # Exposing internal port 80 on host port 81 (optional if you only want tunnel access)
      - "8080:8080"
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      APACHE_ADDITIONAL_NETWORK: ""
      SKIP_DOMAIN_VALIDATION: true

  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    cap_add:
      - NET_ADMIN
    depends_on:
      - nextcloud
    # We store the Tailscale state so we don't have to re-auth every time.
    volumes:
      - ./tailscale/state:/var/lib/tailscale
    network_mode: "container:nextcloud"
    command: >
      sh -c "
        # 1) Start tailscaled in userspace mode in the background
        tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
        # 2) Give it a few seconds to start
        sleep 5
        tailscale set --hostname=nextcloud 
        # 3) Bring Tailscale up, using environment vars for authkey & hostname
        tailscale up
        # 5) NEW SYNTAX for 'funnel'
        tailscale funnel --bg http://127.0.0.1:80    
        tail -f /dev/null
      "
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud-aio:
    external: true