version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"      # Exposing internal port 80 on host port 81 (optional if you only want tunnel access)
      - "8080:8080"
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 127.0.0.1
      APACHE_ADDITIONAL_NETWORK: ""
      SKIP_DOMAIN_VALIDATION: true

  tailscale:
    image: tailscale/tailscale:stable
    container_name: nextcloud-tailscale
    cap_add:
      - NET_ADMIN
    volumes:
      - ./tailscale/state:/var/lib/tailscale
      - ./tailscale.bash:/usr/local/bin/restart_watchdog.sh
    network_mode: "container:nextcloud-aio-apache"
    command: >
      sh -c "sh /usr/local/bin/restart_watchdog.sh "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://nextcloud.tail3092be.ts.net/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud-aio:
    external: true
