version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"      # Exposing internal port 80 on host port 81 (optional if you only want tunnel access)
      - "8080:8080"
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 127.0.0.1
      APACHE_ADDITIONAL_NETWORK: ""
      SKIP_DOMAIN_VALIDATION: true

  tailscale:
    image: tailscale/tailscale:stable
    container_name: nextcloud-tailscale
    cap_add:
      - NET_ADMIN
    volumes:
      - ./tailscale/state:/var/lib/tailscale
    network_mode: "container:nextcloud-aio-apache"
    command: >
      sh -c "
        tailscale down
        tailscale funnel reset
        tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
        sleep 5
        tailscale set --hostname=nextcloud
        tailscale up
        sleep 5
        tailscale funnel --bg http://127.0.0.1:11000  
        tail -f /dev/null
      "
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud-aio:
    external: true
