version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      SKIP_DOMAIN_VALIDATION: true

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=your-cloudflared-tunnel-token
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu
    volumes:
      - ${CLOUDFLARED_CONFIG_DIR}:~/.cloudflared

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer